/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

/**
 *
 * @author andre
 */
public class V_AdminPedidos extends javax.swing.JFrame {

    /**
     * Creates new form V_AdminPedidos
     */
    public V_AdminPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bperfil = new javax.swing.JButton();
        bcerrar = new javax.swing.JButton();
        bpedido = new javax.swing.JButton();
        aTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JTable();
        bVaciarCarrito = new javax.swing.JButton();
        bVaciarCarrito1 = new javax.swing.JButton();
        bVaciarCarrito2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaProductos1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bperfil.setBackground(new java.awt.Color(102, 0, 255));
        bperfil.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bperfil.setForeground(new java.awt.Color(255, 255, 255));
        bperfil.setText("Perfil");
        bperfil.setBorder(null);
        bperfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bperfil.setDefaultCapable(false);
        bperfil.setFocusPainted(false);

        bcerrar.setBackground(new java.awt.Color(102, 0, 255));
        bcerrar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bcerrar.setForeground(new java.awt.Color(255, 255, 255));
        bcerrar.setText("Cerrar");
        bcerrar.setBorder(null);
        bcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bcerrar.setFocusPainted(false);
        bcerrar.setFocusable(false);
        bcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcerrarActionPerformed(evt);
            }
        });

        bpedido.setBackground(new java.awt.Color(102, 0, 255));
        bpedido.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bpedido.setForeground(new java.awt.Color(255, 255, 255));
        bpedido.setText("Pedidos");
        bpedido.setBorder(null);
        bpedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bpedido.setDefaultCapable(false);
        bpedido.setFocusPainted(false);

        aTitulo.setFont(new java.awt.Font("Calibri", 1, 32)); // NOI18N
        aTitulo.setForeground(new java.awt.Color(102, 0, 255));
        aTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aTitulo.setText("Administrar Pedidos");

        listaProductos.setBackground(new java.awt.Color(255, 255, 255));
        listaProductos.setForeground(new java.awt.Color(51, 51, 51));
        listaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaProductos.setToolTipText("1,1");
        listaProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listaProductos.setFocusable(false);
        listaProductos.setGridColor(new java.awt.Color(255, 255, 255));
        listaProductos.setRowHeight(20);
        listaProductos.setSelectionBackground(new java.awt.Color(102, 0, 255));
        listaProductos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        listaProductos.setShowHorizontalLines(false);
        listaProductos.setShowVerticalLines(false);
        jScrollPane2.setViewportView(listaProductos);

        bVaciarCarrito.setBackground(new java.awt.Color(0, 204, 102));
        bVaciarCarrito.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bVaciarCarrito.setForeground(new java.awt.Color(255, 255, 255));
        bVaciarCarrito.setText("Aprobar Pedido");
        bVaciarCarrito.setBorder(null);
        bVaciarCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVaciarCarrito.setFocusPainted(false);
        bVaciarCarrito.setFocusable(false);
        bVaciarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVaciarCarritoActionPerformed(evt);
            }
        });

        bVaciarCarrito1.setBackground(new java.awt.Color(0, 204, 102));
        bVaciarCarrito1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bVaciarCarrito1.setForeground(new java.awt.Color(255, 255, 255));
        bVaciarCarrito1.setText("Vaciar Carrito");
        bVaciarCarrito1.setBorder(null);
        bVaciarCarrito1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVaciarCarrito1.setFocusPainted(false);
        bVaciarCarrito1.setFocusable(false);
        bVaciarCarrito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVaciarCarrito1ActionPerformed(evt);
            }
        });

        bVaciarCarrito2.setBackground(new java.awt.Color(0, 204, 102));
        bVaciarCarrito2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bVaciarCarrito2.setForeground(new java.awt.Color(255, 255, 255));
        bVaciarCarrito2.setText("Vaciar Carrito");
        bVaciarCarrito2.setBorder(null);
        bVaciarCarrito2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVaciarCarrito2.setFocusPainted(false);
        bVaciarCarrito2.setFocusable(false);
        bVaciarCarrito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVaciarCarrito2ActionPerformed(evt);
            }
        });

        listaProductos1.setBackground(new java.awt.Color(255, 255, 255));
        listaProductos1.setForeground(new java.awt.Color(51, 51, 51));
        listaProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaProductos1.setToolTipText("1,1");
        listaProductos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listaProductos1.setFocusable(false);
        listaProductos1.setGridColor(new java.awt.Color(255, 255, 255));
        listaProductos1.setRowHeight(20);
        listaProductos1.setSelectionBackground(new java.awt.Color(102, 0, 255));
        listaProductos1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        listaProductos1.setShowHorizontalLines(false);
        listaProductos1.setShowVerticalLines(false);
        jScrollPane3.setViewportView(listaProductos1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bVaciarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVaciarCarrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVaciarCarrito2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(aTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addComponent(bperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aTitulo)
                    .addComponent(bpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bVaciarCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bVaciarCarrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bVaciarCarrito2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcerrarActionPerformed
        p.cerrar();
    }//GEN-LAST:event_bcerrarActionPerformed

    private void bVaciarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVaciarCarritoActionPerformed
        p.vaciarCarrito();
    }//GEN-LAST:event_bVaciarCarritoActionPerformed

    private void bVaciarCarrito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVaciarCarrito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVaciarCarrito1ActionPerformed

    private void bVaciarCarrito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVaciarCarrito2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVaciarCarrito2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_AdminPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_AdminPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_AdminPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_AdminPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_AdminPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aTitulo;
    private javax.swing.JButton bVaciarCarrito;
    private javax.swing.JButton bVaciarCarrito1;
    private javax.swing.JButton bVaciarCarrito2;
    private javax.swing.JButton bcerrar;
    private javax.swing.JButton bpedido;
    private javax.swing.JButton bperfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listaProductos;
    private javax.swing.JTable listaProductos1;
    // End of variables declaration//GEN-END:variables
}
